_base_: ['../_base_/cityscapes.yml', '../_base_/runtime.yml']

batch_size: 4
iters: 160000

model:
  type: UNet3Plus
  in_channels: 3
  num_classes: 19
  is_batchnorm: True
  is_deepsup: False
  is_CGM: False
